baseURL = "/"
languageCode = "en-us"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Rysnanto"
[[menu.main]]
name = "Login"
url = "https://rysnanto.eu.org/admin"
weight = 3
[module.hugoVersion]
extended = true
min = "0.55.0"
[params]
addDot = true
addFrame = true
google_analytics_id = ""
highlightColor = "#189AB4"
showAuthorOnHomepage = true
showAuthorOnPosts = false
showPostsOnHomepage = false
twitter_handle = "@Rysnanto1"
